#!/usr/bin/env bash
#script
touch /var/run/myscript.pid
echo "$!" > /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM SIGQUIT
#loop
while true;do
	echo "To infinity and beyond"
	sleep 2
done 
