#!/usr/bin/env bash
#for managing my_process
set -e
PIDFILE=/var/run/my_process.pid
DAEMON=/root/alu-shell/processes_and_signals/manage_my_process
case "$1" in 
	start)
	echo "manage_my_process started"
	start-stop-daemon --start --background --exec $DAEMON --make-pidfile --pidfile $PIDFILE
	;;
	stop)
	start-stop-daemon --stop --pidfile $PIDFILE --remove-pidfile 
	echo "manage_my_process stopped"
	;;
	restart)
	start-stop-daemon --stop  --pidfile $PIDFILE --remove-pidfile
	start-stop-daemon --start --background --exec $DAEMON  --background  --make-pidfile --pidfile $PIDFILE   
	echo "manage_my_process restarted"
	;;
	*)
	echo "Usage "$0": manage_my_process {start|stop|restart}"
	exit 1
	;;
esac	
