#!/usr/bin/env bash
#for managing my_process
DAEMON=/sbin:/root/alu-shell/processes_and_signals/manage_my_process
case "$1" in 
	start)
	echo "manage_my_process started"
	start-stop-daemon --start --startas $DAEMON --background --pidfile /var/run/my_process.pid --make-pidfile
	;;
	stop)
	start-stop-daemon --stop $DAEMON  --pidfile /var/run/my_process.pid --remove-pidfile
	echo "manage_my_process stopped"
	;;
	restart)
	start-stop-daemon --stop $DAEMON  --pidfile /var/run/my_process.pid --remove-pidfile
	start-stop-daemon --start --startas $DAEMON --background --pidfile /var/run/my_process.pid --make-pidfile  
	echo "manage_my_process restarted"
	;;
	*)
	echo "Usage: manage_my_process {start|stop|restart}">&2
	exit 1
	;;
esac	
